version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodeapp
permissions:
  - object: /home/ec2-user/nodeapp
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_env.sh
      timeout: 600
      runas: root
  AfterInstall: 
    - location: scripts/change_perm.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 30
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 10
      runas: ec2-user